### ISSUE TITLE
move(TODO)

### ISSUE THREAD

**Issue by hoodie** [tdolist/tdo-rs#3]
it should be possible to move a TODO from one list into another

**Comment by Feliix42** [comment]
Implemented in _tdo-core_ as of [`babc17d`](https://github.com/tdolist/tdo-core/commit/babc17df4bf4a0dab801bbd5a0798e4b03be0f31). Now we just have to add the functionality here after the next release of the core crate. :)

**Comment by h4llow3En** [comment]
closed in 36e554d2bbd3d6c1183b1f44af19ccb0a5569b37
