### ISSUE TITLE
Shell Autocompletion

### ISSUE THREAD

**Issue by Feliix42** [tdolist/tdo-rs#9]
Research the possibility to add a bash/zsh autocompletion.

**Comment by Feliix42** [comment]
@h4llow3En maybe?

**Comment by h4llow3En** [comment]
I will rework this.
as @steigr mentioned, it would be better to add an `eval` to the shellconfig

**Comment by h4llow3En** [comment]
As I found out, it is not possible to use eval because the completions written to stdout are not valid for eval to parse
